#!/bin/bash
unzip ./hdafiles.zip -d .
./KextPatch.sh ./list_4x40ml "${3}"
# disabling Software Update schedule.
softwareupdate --schedule off
# triggering kext cache rebuilding
/usr/libexec/PlistBuddy -c "Set :KextCacheRebuild yes" /tmp/PBI.plist