#!/bin/bash
RightNowIs=`/usr/libexec/PlistBuddy -c "Print :CurrentDateTime" /tmp/PBI.plist`
BackupDir="$HOME/Desktop/Installer Backups/Backup $RightNowIs"
kextdir="$DSTVOLUME/System/Library/Extensions"
# removing the old kext.
if [ -e "$kextdir/RealtekRTL81xx.kext" ]
then
  if [ ! -e "$BackupDir" ]
  then
	mkdir -p "$BackupDir"
  fi
  cp -Rf "$kextdir/RealtekRTL81xx.kext" "$BackupDir"
  rm -rf "$kextdir/RealtekRTL81xx.kext"
fi