#!/bin/bash
cd /tmp/tempDSDT
./patchmatic -extract
find . -name "*.aml" ! -name "DSDT.aml" -delete
./iaslpbi -d -p dsdt_extract ./DSDT.aml
sleep 1
OEMID=`cat ./dsdt_extract.dsl | grep "OEM Table ID" | awk -F'"' '{print $2}'`
cat > ./OemTable.txt << EOF
into method label _DSM parent_label PS2K remove_entry;
into device label PS2K insert
begin
Method (_DSM, 4, NotSerialized)\n
{\n
    If (LEqual (Arg2, Zero)) { Return (Buffer() { 0x03 } ) }\n
    Return (Package()\n
    {\n
        "RM,oem-id", "HPQOEM",\n
        "RM,oem-table-id", "$OEMID",\n
    })\n
}\n
end;
EOF
VanillaCheck=`cat ./dsdt_extract.dsl | grep 'If (CondRefOf (FPED))'`
if [ "$VanillaCheck" == "" -a -f ./4x*.txt ] || [ "$VanillaCheck" != "" -a ! -f ./4x*.txt ]
then
	cp ./warning.txt "$HOME/Desktop/DSDT Warning.txt"
	cp ./Mini-SSDT-DualLink.aml "$HOME/Desktop/"
	cp ./Mini-SSDT-IMEI.aml "$HOME/Desktop/"
else
	cp ./dsdt_extract.dsl ./dsdt_patch.dsl
	for patch in "4x30s.txt" \
		"4x40s_IvyBridge.txt" \
		"4x40s_SandyBridge.txt" \
		"03a_HDMI.txt" \
		"03b_1080p+HDMI.txt" \
		"04a_FanPatch.txt" \
		"04b_FanQuiet.txt" \
		"04c_FanSpeed.txt" \
		"08a_AR9285.txt" \
		"08b_BCM4322x.txt" \
		"09_USB3_4x40s_Mieze.txt" \
		"10_LPC_4x40s_Sandy_SL.txt" \
		"12_Brightness.txt" \
		"12c_generic_BCL.txt" \
		"OemTable.txt"
	do
		if [ -f $patch ]
		then
			./patchmatic ./dsdt_patch.dsl ./$patch ./dsdt_patch.dsl
		fi
	done
	./iaslpbi -p DSDT ./dsdt_patch.dsl
	cp ./DSDT.aml /Extra/DSDT.aml
fi
rm -rf /tmp/tempDSDT