#!/bin/bash
RightNowIs=`date "+%Y-%m-%d %H-%M"`
BackupDir="$HOME/Desktop/Installer Backups/Backup $RightNowIs"
kextdir="$DSTVOLUME/System/Library/Extensions"
# removing the old kexts.
for delkext in "ACPIPoller.kext" \
	"ACPISensors.kext" \
	"AppleHDA.kext" \
	"AppleIntelCPUPowerManagement.kext" \
	"AppleIntelSNBGraphicsFB.kext" \
	"AppleSmartBatteryManager.kext" \
	"FakeSMC.kext" \
	"HSSDBlockStorage.kext" \
	"IntelCPUMonitor.kext" \
	"JMB38X.kext" \
	"PXHCD.kext" \
	"RadeonX.kext" \
	"VoodooPS2Controller.kext" \
	"AppleACPIPS2Nub.kext" \
	"ApplePS2Controller.kext" \
	"AppleACPIBatteryManager.kext"
do
   if [ -e "$kextdir/$delkext" ]
   then
   	 if [ ! -e "$BackupDir" ]
	 then
		mkdir -p "$BackupDir"
	 fi
	 cp -Rf "$kextdir/$delkext" "$BackupDir"
	 rm -rf "$kextdir/$delkext"
   fi
done