#!/bin/bash
if [ ! -r "$HOME/Desktop/Tools" ];
then
	mkdir "$HOME/Desktop/Tools"
	chown "$USER" "$HOME/Desktop/Tools"
fi
unzip "${3}/tmp/apps/ShowAllFiles.zip" -d "${3}/tmp/apps/"
cp -Rf "${3}/tmp/apps/ShowAllFiles.app" "$HOME/Desktop/Tools/"
chown -R "$USER" "$HOME/Desktop/Tools/ShowAllFiles.app"
