#!/bin/bash
RightNowIs=`/usr/libexec/PlistBuddy -c "Print :CurrentDateTime" /tmp/PBI.plist`
BackupDir="$HOME/Desktop/Installer Backups/Backup $RightNowIs"
kextdir="$DSTVOLUME/System/Library/Extensions"
RTCpatched=`md5 -q $kextdir/AppleRTC.kext/Contents/MacOS/AppleRTC`
# patching AppleRTC.kext for 4x40s
if [ "$RTCpatched" == "43d7bd19be683cfb8dae1826da40ab24" ]
then
	cp -Rf "$kextdir/AppleRTC.kext" "$BackupDir"
	perl -pi -e 's|\x75\x30\x89\xd8|\xeb\x30\x89\xd8|' "$kextdir/AppleRTC.kext/Contents/MacOS/AppleRTC"
fi
# disabling Software Update schedule.
softwareupdate --schedule off
# triggering kext cache rebuilding
/usr/libexec/PlistBuddy -c "Set :KextCacheRebuild yes" /tmp/PBI.plist