#!/bin/bash
RightNowIs=`/usr/libexec/PlistBuddy -c "Print :CurrentDateTime" /tmp/PBI.plist`
BackupDir="$HOME/Desktop/Installer Backups/Backup $RightNowIs"
kextdir="${3}/System/Library/Extensions"
ChamPlist="${3}/Extra/org.chameleon.Boot.plist"
# removing the old kexts.
for delkext in "AppleHDA.kext" \
	"AppleIntelCPUPowerManagement.kext" \
	"AppleIntelFramebufferCapri.kext" \
	"AppleIntelSNBGraphicsFB.kext"
do
   if [ -e "$kextdir/$delkext" ]
   then
   	 if [ ! -e "$BackupDir" ]
   	 then
   		mkdir -p "$BackupDir"
   	 fi
	 cp -Rf "$kextdir/$delkext" "$BackupDir"
	 rm -rf "$kextdir/$delkext"
   fi
done
# backing up any old org.chameleon.Boot.plist, if exists
if [ -f "$ChamPlist" ]
then
	if [ ! -e "$BackupDir" ]
	then
		mkdir -p "$BackupDir"
	fi
 	cp "$ChamPlist" "$BackupDir"
 	rm -rf "$ChamPlist"
fi