#!/bin/bash
RightNowIs=`/usr/libexec/PlistBuddy -c "Print :CurrentDateTime" /tmp/PBI.plist`
BackupDir="$HOME/Desktop/Installer Backups/Backup $RightNowIs"
kextdir="$DSTVOLUME/System/Library/Extensions"
# removing the old kexts.
for delkext in "AppleHDA.kext" \
	"AppleIntelCPUPowerManagement.kext" \
	"AppleIntelFramebufferCapri.kext" \
	"AppleACPIPS2Nub.kext" \
	"ApplePS2Controller.kext" \
	"AppleACPIBatteryManager.kext"
do
   if [ -e "$kextdir/$delkext" ]
   then
   	 if [ ! -e "$BackupDir" ]
   	 then
   		mkdir -p "$BackupDir"
   	 fi
	 cp -Rf "$kextdir/$delkext" "$BackupDir"
	 rm -rf "$kextdir/$delkext"
   fi
done