#!/bin/bash
week=QRTVWXY12345678
chars=ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
week_letter=`echo ${week:$(($RANDOM%${#week})):1}`
function random_char { echo ${chars:$(($RANDOM%${#chars})):1}; }
serial="C02H"$week_letter$(random_char)$(random_char)$(random_char)"DTY3"
/usr/libexec/PlistBuddy -c "Set :SMserial $serial" ${3}/Extra/smbios.plist