#!/bin/bash
# rebilding the kext cache, if triggered
RebuildOn=`/usr/libexec/PlistBuddy -c "Print :KextCacheRebuild" /tmp/PBI.plist`
if [ "$RebuildOn" == "yes" ]
then
	touch "$DSTVOLUME/System/Library/Extensions"
fi
# deleting temporary files
rm -rf /tmp/PBI.plist
rm -rf /tmp/Apps