#!/bin/bash
PBIplist="/tmp/PBI.plist"
if [ -e "$PBIplist" ]
then
	rm -rf "$PBIplist"
fi
/usr/libexec/PlistBuddy -c "Add :CurrentDateTime string `date '+%Y-%m-%d %H-%M'`" "$PBIplist"
/usr/libexec/PlistBuddy -c "Add :KextCacheRebuild string 'no'" "$PBIplist"