#!/bin/bash
if [ ! -r "$HOME/Desktop/Tools" ];
then
	mkdir "$HOME/Desktop/Tools"
	chown "$USER" "$HOME/Desktop/Tools"
fi
unzip "${3}/tmp/apps/HWMonitor_SL.zip" -d "${3}/tmp/apps/"
cp -rf "${3}/tmp/apps/HWMonitor.app" "$HOME/Desktop/Tools/"
chown -R "$USER" "$HOME/Desktop/Tools/HWMonitor.app"
