#!/bin/bash
if [ ! -r "$HOME/Desktop/Tools" ];
then
mkdir "$HOME/Desktop/Tools"
chown "$USER" "$HOME/Desktop/Tools"
fi
unzip "$DSTVOLUME/tmp/apps/MaciASL.zip" -d "$DSTVOLUME/tmp/apps/"
cp -Rf "$DSTVOLUME/tmp/apps/MaciASL.app" "$HOME/Desktop/Tools/"
chown -R "$USER" "$HOME/Desktop/Tools/MaciASL.app"
