#!/bin/bash
IvyBridge=`/usr/libexec/PlistBuddy -c "Print :IvyInstall" /tmp/PBI.plist`
if [ "$IvyBridge" == "yes" ]
then
	rm -rf /System/Library/Extensions/PXHCD.kext
fi
# triggering kext cache rebuilding
/usr/libexec/PlistBuddy -c "Set :KextCacheRebuild yes" /tmp/PBI.plist