#!/bin/bash
RightNowIs=`/usr/libexec/PlistBuddy -c "Print :CurrentDateTime" /tmp/PBI.plist`
BackupDir="$HOME/Desktop/Installer Backups/Backup $RightNowIs"
kextdir="$DSTVOLUME/System/Library/Extensions"
ath21="$kextdir/IO80211Family.kext/Contents/PlugIns/AirPortAtheros21.kext/Contents/Info.plist"
ath9388="$kextdir/IO80211Family.kext/Contents/PlugIns/AirPortAtheros9388.kext/Contents/Info.plist"
IsNotPatched=`/usr/libexec/PlistBuddy -c "Print ':IOKitPersonalities:Atheros Wireless LAN PCI:IONameMatch:0'" "$ath21"`
# patching IO80211Family.kext.
if [ "$IsNotPatched" == "pci168c,2a" ]
then
	cp -Rf "$kextdir/IO80211Family.kext" "$BackupDir"
	/usr/libexec/PlistBuddy -c "Remove ':IOKitPersonalities:Atheros Wireless LAN PCI:IONameMatch:0'" "$ath21"
	/usr/libexec/PlistBuddy -c "Add ':IOKitPersonalities:Atheros Wireless LAN PCI:IONameMatch:1' string 'pci168c,2a'" "$ath9388"
fi
# triggering kext cache rebuilding
/usr/libexec/PlistBuddy -c "Set :KextCacheRebuild yes" /tmp/PBI.plist