#!/bin/bash
RightNowIs=`/usr/libexec/PlistBuddy -c "Print :CurrentDateTime" /tmp/PBI.plist`
BackupDir="$HOME/Desktop/Installer Backups/Backup $RightNowIs"
kextdir="${3}/System/Library/Extensions"
ARTL8169="$kextdir/IONetworkingFamily.kext/Contents/PlugIns/AppleRTL8169Ethernet.kext"
# removing AppleRTL8169Ethernet.kext in favor of RealtekRTL8111.kext
if [ -e "$ARTL8169" ]
then
	cp -Rf "$kextdir/IONetworkingFamily.kext" "$BackupDir"
	rm -Rf "$ARTL8169"
fi
# disabling Software Update schedule.
softwareupdate --schedule off
# triggering kext cache rebuilding
/usr/libexec/PlistBuddy -c "Set :KextCacheRebuild yes" /tmp/PBI.plist