#!/bin/bash
# removing old kexts, if exist. If there are no old kext, the vanilla kexts will be removed
kextdir="$DSTVOLUME/System/Library/Extensions"
for delkext in "ACPIPoller.kext" "ACPISensors.kext" "AppleHDA.kext" "AppleIntelCPUPowerManagement.kext" "AppleSmartBatteryManager.kext" "FakeSMC.kext" "HSSDBlockStorage.kext" "IntelCPUMonitor.kext" "JMB38X.kext" "PXHCD.kext" "VoodooPS2Controller.kext"
do
   if [ -e  "$kextdir/$delkext" ]
   then
      rm -rf "$kextdir/$delkext"
   fi
done