#!/bin/bash
kextdir="$DSTVOLUME/System/Library/Extensions"
KBplist="$kextdir/VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Keyboard.kext/Contents/Info.plist"
cond1=`/usr/libexec/PlistBuddy -c "Print ':IOKitPersonalities:ApplePS2Keyboard:Custom PS2 Map:1'" "$KBplist"`
cond2=`/usr/libexec/PlistBuddy -c "Print ':IOKitPersonalities:ApplePS2Keyboard:Custom PS2 Map:4'" "$KBplist"`
case "$cond1" in
";The following 12 items map Fn+fkeys to fkeys")
/usr/libexec/PlistBuddy -c "Delete ':IOKitPersonalities:ApplePS2Keyboard:Custom PS2 Map'" "$KBplist"
/usr/libexec/PlistBuddy -c "Add ':IOKitPersonalities:ApplePS2Keyboard:Custom PS2 Map' array" "$KBplist"
/usr/libexec/PlistBuddy -c "Add ':IOKitPersonalities:ApplePS2Keyboard:Custom PS2 Map:0' string ';Items must be strings in the form of scanfrom=scanto'" "$KBplist"
/usr/libexec/PlistBuddy -c "Set ':IOKitPersonalities:ApplePS2Keyboard:SleepPressTime' 0" "$KBplist"
/usr/libexec/PlistBuddy -c "Set :KextCacheRebuild yes" /tmp/PBI.plist
;;
";Italian keyboard fix")
if [ "$cond2" == ";The following 12 items map Fn+fkeys to fkeys" ]
then
	/usr/libexec/PlistBuddy -c "Delete ':IOKitPersonalities:ApplePS2Keyboard:Custom PS2 Map'" "$KBplist"
	/usr/libexec/PlistBuddy -c "Add ':IOKitPersonalities:ApplePS2Keyboard:Custom PS2 Map' array" "$KBplist"
	/usr/libexec/PlistBuddy -c "Add ':IOKitPersonalities:ApplePS2Keyboard:Custom PS2 Map:0' string ';Items must be strings in the form of scanfrom=scanto'" "$KBplist"
	/usr/libexec/PlistBuddy -c "Add ':IOKitPersonalities:ApplePS2Keyboard:Custom PS2 Map:1' string ';Italian keyboard fix'" "$KBplist"
	/usr/libexec/PlistBuddy -c "Add ':IOKitPersonalities:ApplePS2Keyboard:Custom PS2 Map:2' string '56=29'" "$KBplist"
	/usr/libexec/PlistBuddy -c "Add ':IOKitPersonalities:ApplePS2Keyboard:Custom PS2 Map:3' string '29=56'" "$KBplist"
	/usr/libexec/PlistBuddy -c "Set ':IOKitPersonalities:ApplePS2Keyboard:SleepPressTime' 0" "$KBplist"
	/usr/libexec/PlistBuddy -c "Set :KextCacheRebuild yes" /tmp/PBI.plist
else
	echo "No patch is required!"
	exit 0
fi
;;
*)
echo "No patch is required!"
exit 0
;;
esac