#!/bin/sh
kextdir="$DSTVOLUME/System/Library/Extensions"
KBplist="$kextdir/VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Keyboard.kext/Contents/Info.plist"
cond1=`/usr/libexec/PlistBuddy -c "Print ':IOKitPersonalities:ApplePS2Keyboard:Custom PS2 Map:1'" "$KBplist"`
AddPlistString () {
/usr/libexec/PlistBuddy -c "Add ':IOKitPersonalities:ApplePS2Keyboard:Custom PS2 Map:$2' string '$1'" "$KBplist"
}
if [ "$cond1" == ";The following 12 items map Fn+fkeys to fkeys" ]
then
	echo "No patching is required!"
	exit 0
else
	AddPlistString ";The following 12 items map Fn+fkeys to fkeys" 1
	AddPlistString "e05f=3b" 2
	AddPlistString "e012=3c" 3
	AddPlistString "e017=3d" 4
	AddPlistString "e06e=3e" 5
	AddPlistString "e00a=3f" 6
	AddPlistString "e009=40" 7
	AddPlistString "e020=41" 8
	AddPlistString "e02e=42" 9
	AddPlistString "e030=43" 10
	AddPlistString "e010=44" 11
	AddPlistString "e022=57" 12
	AddPlistString "e019=58" 13
	AddPlistString ";The following 12 items map fkeys to Fn+fkeys" 14
	AddPlistString "3b=e05f" 15
	AddPlistString "3c=e012" 16
	AddPlistString "3d=e017" 17
	AddPlistString "3e=e06e" 18
	AddPlistString "3f=e00a" 19
	AddPlistString "40=e009" 20
	AddPlistString "41=e020" 21
	AddPlistString "42=e02e" 22
	AddPlistString "43=e030" 23
	AddPlistString "44=e010" 24
	AddPlistString "57=e022" 25
	AddPlistString "58=e019" 26
	/usr/libexec/PlistBuddy -c "Set ':IOKitPersonalities:ApplePS2Keyboard:SleepPressTime' 3000" "$KBplist"
	/usr/libexec/PlistBuddy -c "Set :KextCacheRebuild yes" /tmp/PBI.plist
fi