#!/bin/bash
if [ ! -r "$HOME/Desktop/Tools" ];
then
	mkdir "$HOME/Desktop/Tools"
	chown "$USER" "$HOME/Desktop/Tools"
fi
unzip "${3}/tmp/apps/Localtime-Toggle.pkg.zip" -d "${3}/tmp/apps/"
cp -f "${3}/tmp/apps/Localtime-Toggle.pkg" "$HOME/Desktop/Tools/"
chown "$USER" "$HOME/Desktop/Tools/Localtime-Toggle.pkg"