#!/bin/bash
RightNowIs=`/usr/libexec/PlistBuddy -c "Print :CurrentDateTime" /tmp/PBI.plist`
BackupDir="$HOME/Desktop/Installer Backups/Backup $RightNowIs"
CurrentSSDT="${3}/Extra/SSDT.aml"
./ssdtPRGen.sh
if [ -e "$CurrentSSDT" ]
then
	if [ ! -e "$BackupDir" ]
	then
		mkdir -p "$BackupDir"
	fi
	cp -f "$CurrentSSDT" "$BackupDir"
	rm -f "$CurrentSSDT"
fi
cp -f "./SSDT_PR.aml" "$CurrentSSDT"
chown "$USER" "$CurrentSSDT"