#!/bin/bash
pmset -a hibernatemode 0
if [ -f /private/var/vm/sleepimage ]; then
    rm /private/var/vm/sleepimage
fi
if [ ! -d /private/var/vm/sleepimage ]; then
    mkdir /private/var/vm/sleepimage
fi