#!/bin/bash
if [ ! -r "$HOME/Desktop/Tools" ];
then
mkdir "$HOME/Desktop/Tools"
chown "$USER" "$HOME/Desktop/Tools" 
fi
cp -rf "$DSTVOLUME/tmp/apps/Quartz Debug.app" "$HOME/Desktop/Tools/"
chown -R "$USER" "$HOME/Desktop/Tools/Quartz Debug.app"